<a href="https://colab.research.google.com/github/Nabarundutta/Machine-Learning/blob/main/SimpleRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [3]:
model = Sequential()
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 3)                   │              27 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()[0]

array([[-0.71081364,  0.32202083,  0.67888707],
       [-0.26517618,  0.1485942 , -0.3435974 ],
       [-0.46910354,  0.02132076, -0.1103828 ],
       [ 0.09003597,  0.44676238,  0.01188171],
       [ 0.2784446 ,  0.6643011 , -0.7881994 ]], dtype=float32)

In [7]:
model.get_weights()[1]

array([[ 0.26389158, -0.7382712 , -0.6207391 ],
       [-0.6708345 ,  0.32193914, -0.6680841 ],
       [ 0.69306743,  0.5927149 , -0.41030067]], dtype=float32)

In [8]:
model.get_weights()[2]

array([0., 0., 0.], dtype=float32)

In [9]:
model.get_weights()[3]

array([[ 1.002796  ],
       [ 0.40662766],
       [-0.5811922 ]], dtype=float32)

In [10]:
model.get_weights()[4]

array([0.], dtype=float32)